[build]
  command = "npm run build"
  publish = "dist"
  ignore = "requirements.txt"

# SPA 라우팅을 위한 리다이렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Node.js 환경 설정
[build.environment]
  NODE_VERSION = "18"
  # Python 종속성 무시
  SKIP_PYTHON_INSTALL = "true" 